import Head from 'next/head'
import { Fraunces } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Banner from '../components/Banner'
import Image from 'next/image'
import Link from 'next/link'
import Content from '../components/Content'



export default function Home() {
  return (
    <>
      <Head>
        <title>Sunnyside Agency App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <Banner/>
      <main className={styles.main} >
        
        <Content />
        
      </main>
    </>
  )
}
